base_config: configs/lipgen/transformer_tts.yaml

# train with fs
vid_use_gt_dur: true
cut_test_set: 1000
gt_ar: false

# model
hidden_size: 256
arch: '8 8 8 8 8 8 8 8' # no conv1d
dropout: 0.2

dec_last_ln: true
predictor_sg: true
# duration
predictor_hidden: 256
dur_predictor_kernel: 3
use_gt_dur: false
sep_dur_loss: true
# pitch and energy
use_pitch_embed: true
pitch_embed_type: 0
use_uv: true
use_energy_embed: true
pitch_loss: 'l1'

# loss
lambda_dur: 1.0
lambda_pitch: 1.0
lambda_uv: 1.0
lambda_energy: 1.0
mel_loss: l1

# train and eval
pretrain_fs_ckpt: ''
warmup_updates: 2000
max_tokens: 28000
max_sentences: -1
max_eval_sentences: 1
max_updates: 200000
gen_dir_name: ''